activity/urls.py
from django.urls import path
from .views import index, home, delete, update_budget

app_name = 'activity'

urlpatterns = [
    path('delete/<int:id_num>', delete, name='delete'),
    path('update/budget/<int:id_num>', update_budget, name='update-name'),
    path('home/', home, name='home'),
    path('', index, name='index'),
]

expense_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('activity.urls')),
    path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from .views import register

app_name = 'users'


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
]

activity/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.db.models import Sum


# Create your models here.
from django.db.models import ForeignKey


class Budget(models.Model):
    income = models.FloatField("monthly income", default=0, blank=True)
    savings = models.FloatField("monthly savings", default=0, blank=True,)
    date = models.DateField()
    balance = models.FloatField(blank=True, default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def total_expenses(self):
        return self.activities.filter(type='expense')\
            .aggregate(Sum('amount'))\
            .get('amount__sum')

    def total_income(self):
        incomes = 0
        if len(self.activities.filter(type='income')) > 0:
            incomes = self.activities.filter(type='income') \
                .aggregate(Sum('amount')) \
                .get('amount__sum')
        return incomes + self.income

    def __str__(self):
        return f"{self.date.strftime('%B')} budget of {self.user.username}"


class Activity(models.Model):
    TYPE_CHOICES = (
        ("expense", 'Expense'),
        ("income", 'Income')
    )
    title = models.CharField(max_length=100)
    date = models.DateTimeField(default=timezone.now)
    budget = ForeignKey(Budget, on_delete=models.CASCADE, related_name='activities')
    amount = models.FloatField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='expenses')
    type = models.CharField(max_length=10, choices=TYPE_CHOICES, default='expense')

    def __str__(self):
        return self.title


class Expense(models.Model):
    pass

activity/forms.py
from django import forms
from .models import Budget, Activity
from django.utils import timezone
from datetime import date
from django.db.models import Sum
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Submit, Column


class ActivityForm(forms.ModelForm):
    amount = forms.FloatField(widget=forms.NumberInput(attrs={'min': '0.1', 'step': '0.01'}))
    # type = forms.ChoiceField()

    class Meta:
        model = Activity
        fields = ['title', 'amount', 'type']
        labels = {
            'title': 'Transaction'
        }

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('title', css_class='col-12'),
            ),
            Row(
                Column('amount', css_class='col-12'),
            ),
            Row(
                Column('type', css_class='col-12'),
            ),
            Submit('submit', 'Add', css_class='btn-success')
        )
        self.fields['title'].widget.attrs['autofocus'] = ''

    def save(self, commit=True):
        instance = super().save(commit=False)
        current_month = timezone.datetime(year=instance.date.year,
                                          month=instance.date.month,
                                          day=1)
        instance.user = self.request.user
        budget = Budget.objects.get_or_create(date=current_month, user=instance.user)[0]
        instance.budget = budget

        if commit:
            instance.save()
        return instance


class BudgetForm(forms.ModelForm):

    class Meta:
        model = Budget
        fields = ['income', 'savings']

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def save(self, commit=True):
        print('saving budget')
        instance = super().save(commit=False)
        if not instance.date:
            instance.date = date(year=timezone.now().year,
                                 month=timezone.now().month,
                                 day=1)
        if not instance.user:
            instance.user = self.request.user

        expenses = 0
        if instance.activities.all().filter(type='expense')\
                .aggregate(Sum('amount'))\
                .get('amount__sum'):
            expenses = instance.activities.all().filter(type='expense')\
                .aggregate(Sum('amount'))\
                .get('amount__sum')

        income = 0
        if instance.activities.all().filter(type='income')\
                .aggregate(Sum('amount'))\
                .get('amount__sum'):
            income = instance.activities.all().filter(type='income')\
                .aggregate(Sum('amount'))\
                .get('amount__sum')

        instance.balance = (instance.income -
                            instance.savings -
                            expenses + income)
        if commit:
            instance.save()
        return instance

activity/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.utils import timezone
from .utils import get_prev_month_budget_balance
from .models import Budget, Activity
from .forms import BudgetForm, ActivityForm


# Create your views here.
def index(request):
    user = request.user
    if user.is_authenticated:
        return redirect('activity:home')
    return render(request, 'activity/index.html')


@login_required()
def home(request):
    user = request.user
    current_month = timezone.datetime(year=timezone.now().year,
                                      month=timezone.now().month,
                                      day=1)
    page_num = request.GET.get('page')
    prev_balance = get_prev_month_budget_balance(current_month, user)
    budget, created = Budget.objects.get_or_create(date=current_month,
                                                   user=user)
    if created:
        budget.balance = prev_balance
        budget.save()

    records = budget.activities.all().order_by('-date')
    paginator = Paginator(records, 10)

    try:
        records = paginator.page(page_num)
    except PageNotAnInteger:
        records = paginator.page(1)
    except EmptyPage:
        records = paginator.page(paginator.num_pages)

    form = ActivityForm(request)

    if request.method == 'POST':
        form = ActivityForm(request, request.POST)

        if form.is_valid():
            form.save()

            return redirect('activity:home')

    return render(request,
                  'activity/home.html',
                  {
                      'budget': budget,
                      'form': form,
                      'records': records,
                      'paginator': paginator,
                  })


@login_required()
def delete(request, id_num):
    # if request.method == 'POST':
    account_user = request.user
    Activity.objects.get(user=account_user, pk=id_num).delete()
    return redirect('activity:home')


@login_required()
def update_budget(request, id_num):
    budget = Budget.objects.get(pk=id_num)
    form = BudgetForm(instance=budget)

    if request.method == 'POST':
        form = BudgetForm(request, request.POST, instance=budget)
        if form.is_valid():
            form.save()
        return redirect('activity:home')

    return render(request, 'activity/update_budget.html', {'form': form})

templates/activity/home.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% load money %}
{% load humanize %}
{% load crispy_forms_tags %}


{% block main %}
<main class="px-3 px-md-0">

    <div class="container-lg p-1">
        <div class="top row">
            <div class="col-md-6 col-lg-4 mt-3">
{#            <div class="hang">#}
                <div class="budget border row ">
                <div class="wrap">
                    <h3 class="display-5">{{ budget.date|date:'M' }}</h3> <span class="dot">&bull;</span>
                    <h3 class="display-5">{{ budget.date|date:'Y' }}</h3>
                    <a href="{% url 'activity:update-name' budget.id %}" class="btn btn-light to-right">Update <br>Budget</a>
                </div>
                <div class="row budget__summary">
                    <div class="col-12 budget__summary--detail tot-expenses">
                        <h5 >Expenses:</h5>
                        <p >{% if budget.total_expenses %}{{ budget.total_expenses|floatformat:2|intcomma|currency|safe }} {% else %} 0.00 {% endif %}</p>
                    </div>
                    <div class="col-12 others row">
                        <div class=" col-4 budget__summary--detail">
                            <h5>Income:</h5>
                            <p>{% if budget.total_income %}{{ budget.total_income|floatformat:2|intcomma|currency|safe|default:'Not set' }}{% else %}{{ ""|currency|safe }}Not set{% endif %}</p>
                        </div>
                        <div class=" col-4 budget__summary--detail">
                            <h5>Savings:</h5>
                            <p>{{ budget.savings|floatformat:2|intcomma|currency|safe }}</p>
                        </div>
                        <div class="col-4 budget__summary--detail">
                        <h5>Balance:</h5>
                        <p>{% if budget.balance %}{{ budget.balance|floatformat:2|intcomma|currency|safe }}{% else %}{{ ""|currency|safe }}Not set{% endif %}</p>
                    </div>
                    </div>
                </div>
        </div>
                <div class="expense-form border mt-4">
                    <form method="post">
                        {% csrf_token %}
                        {% crispy form %}
                    </form>
                </div>
{#            </div>#}
            </div>

            <div class="col mt-3 record-wrap">
                <div class="right">
                <h1>RECORDS</h1>
                <div class="wrapper mt-3 mb-3 mx-0">
  {% if records.has_other_pages %}
      <nav aria-label="Page navigation" class="col d-flex mt-md-0 d-md-inline-flex px-0 pt-0">
        <ul class="pagination mb-0">

          {% if records.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ 1 }}">&laquo;</a></li>

              {% if records.previous_page_number|add:-2 >= 1 %}
                  <li class="page-item"><a class="page-link" href="?page={{ records.previous_page_number|add:-2}}">{{ records.previous_page_number|add:-2 }}</a></li>
              {% endif %}

              {% if records.previous_page_number|add:-1 >= 1 %}
                  <li class="page-item"><a class="page-link" href="?page={{ records.previous_page_number|add:-1}}">{{ records.previous_page_number|add:-1 }}</a></li>
              {% endif %}

            <li class="page-item"><a class="page-link" href="?page={{ records.previous_page_number }}">{{ records.previous_page_number }}</a></li>

          {% else %}

            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>

          {% endif %}
              <li class="page-item active"><span class="page-link" >{{ records.number }} <span class="sr-only">(current)</span></span></li>
      {#        <li><a href="?page={{ i }}">{{ i }}</a></li>#}
          {% if records.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ records.next_page_number }}">{{ records.next_page_number }}</a></li>
            {% if records.next_page_number|add:1 <= paginator.num_pages %}
              <li class="page-item"><a class="page-link" href="?page={{ records.next_page_number|add:1}}">{{ records.next_page_number|add:1 }}</a></li>
            {% endif %}
            {% if records.next_page_number|add:2 <= paginator.num_pages %}
              <li class="page-item"><a class="page-link" href="?page={{ records.next_page_number|add:2}}">{{ records.next_page_number|add:2 }}</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="?page={{ paginator.num_pages }}">&raquo;</a></li>
          {% else %}
            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
          {% endif %}
        </ul>
      </nav>
  {% endif %}

</div>

                {% if records %}
                    {% for record in records %}
                    <div class="record  row {{ record.type }}" >
                        <div class="col-7 col-md-7">
                            <div class="title">
                                {{ record.title }}
                            </div>

                            <div class="date mt-1">
                                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
width="20" height="20"
viewBox="0 0 172 172"
style=" fill:#000000;"><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,172v-172h172v172z" fill="none"></path><g fill="#666666"><path d="M43,7.16667v14.33333h-7.16667c-7.88333,0 -14.33333,6.45 -14.33333,14.33333v100.33333c0,7.88333 6.45,14.33333 14.33333,14.33333h100.33333c7.88333,0 14.33333,-6.45 14.33333,-14.33333v-100.33333c0,-7.88333 -6.45,-14.33333 -14.33333,-14.33333h-7.16667v-14.33333h-14.33333v14.33333h-57.33333v-14.33333zM35.83333,57.33333h100.33333v78.83333h-100.33333z"></path></g></g></svg>
                                {{ record.date |date:'l, jS' }}
                            </div>
                        </div>
                        <div class="col-3 col-md-3 amount">
                            {{ record.amount|floatformat:2|intcomma|currency|safe }}
                        </div>
                        <div class="col-2 del"  data-id="{{ record.id }}">
                                <a class="" data-toggle="modal" data-target="#deleteModal"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
width="28" height="28"
viewBox="0 0 172 172"
style=" fill:#000000;"><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,172v-172h172v172z" fill="none"></path><g fill="#95a5a6" id="icon-filler"><path d="M71.66667,14.33333l-7.16667,7.16667h-28.66667c-3.956,0 -7.16667,3.21067 -7.16667,7.16667c0,3.956 3.21067,7.16667 7.16667,7.16667h100.33333c3.956,0 7.16667,-3.21067 7.16667,-7.16667c0,-3.956 -3.21067,-7.16667 -7.16667,-7.16667h-28.66667l-7.16667,-7.16667zM35.83333,50.16667v93.16667c0,7.88333 6.45,14.33333 14.33333,14.33333h71.66667c7.88333,0 14.33333,-6.45 14.33333,-14.33333v-93.16667zM67.43945,74.63411c1.82929,0 3.65914,0.6917 5.05306,2.08561l13.50749,13.50749l13.50749,-13.50749c2.78783,-2.78783 7.31828,-2.78783 10.10612,0c2.78783,2.78783 2.78783,7.31828 0,10.10612l-13.50749,13.50749l13.50749,13.50749c2.78783,2.78783 2.78783,7.31828 0,10.10612c-2.78783,2.78783 -7.31828,2.78783 -10.10612,0l-13.50749,-13.50749l-13.50749,13.50749c-2.78783,2.78783 -7.31828,2.78783 -10.10612,0c-2.78783,-2.78783 -2.78783,-7.31828 0,-10.10612l13.50749,-13.50749l-13.50749,-13.50749c-2.78783,-2.78783 -2.78783,-7.31828 0,-10.10612c1.39392,-1.39392 3.22377,-2.08561 5.05306,-2.08561z"></path></g></g></svg></a>
                        </div>
                        </div>
                    {% endfor %}


                    {% else %}
                    <div>No Records Yet</div>
                {% endif %}
                </div>
            </div>
        </div>
    </div>


</main>

    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete:</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">

                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                            <button type="button" class="btn btn-danger" data-id="" >Yes, Delete</button>
                          </div>
                        </div>
                      </div>
                    </div>
{% endblock %}

{% block footer %}

{% endblock %}

{% block script %}
    <script>

   const modalBody = document.querySelector('.modal-body')
    const modalDeleteBtn= document.querySelector('.modal .btn-danger')

    let delBtns = document.querySelectorAll('.del a')
    delBtns.forEach(btn=>{
        btn.addEventListener('click', (e)=>{
            e.preventDefault()
            modalBody.innerHTML = '<em>' + btn.parentElement.parentElement.querySelector('.title').innerText + '</em><br>'+  `<span class="date"> posted ${btn.parentElement.parentElement.querySelector('.date').innerText}? </span>`
            console.log(btn.parentElement.parentElement.querySelector('.title').innerText)
            modalDeleteBtn.dataset.id = btn.parentElement.dataset.id

            modalDeleteBtn.addEventListener('click', ()=> {
                fetch('{% url 'activity:delete' 1 %}'.replace('/1', `/${modalDeleteBtn.dataset.id}`))
                {#.then(()=>window.location = document.URL);#}
                .then(data=> window.location.href = data.url)
            })
        })
    })
    </script>

{% endblock %}

templates/activity/index.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}


{% block main %}
<main class="px-3 px-md-0">

    <div class="container p-xs-1 p-sm-3">
      <section class="hero row">
        <div class="hero__text col-lg-7 col">
          <div>
            <h1 class="hero__text--main" id="typing"></h1>
            <p class="hero__text--sec pr-lg-5 mr-lg-5">
              Track your monthly inflow and outflow of cash to be able to take effective financial decisions
            </p>
            <div class="cta mt-5 mt-sm-0">
              <a href="{% url 'users:login' %}" class="btn hero__btn hero__btn--primary">Sign in</a>
              <a href="{% url 'users:register' %}"  class="btn hero__btn hero__btn--empty">Register</a>
            </div>

          </div>
        </div>
        <div class="hero__img col d-lg-block d-none">
          <img src="{% static 'img/money.png' %}" class="hero__img--pic" alt="money bag">
        </div>
      </section>
    </div>
</main>
{% endblock %}

{% block footer %}

{% endblock %}

templates/activity/update_budget.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Sign In
{% endblock %}

{% block main %}
    <main class="login-page">

        <form class="sign" method="post">
            <div class="form-group"><h2>Update Monthly Budget</h2></div>
            {% csrf_token %}
            {{ form|crispy }}
          <div class="form-group">
              <button type="submit" class="btn btn-primary">Update</button>
          </div>
            <div class="bg"></div>
        </form>
    </main>
{% endblock %}