activity/urls.py
from django.urls import path
from .views import index, home, delete, update_budget

app_name = 'activity'

urlpatterns = [
    path('delete/<int:id_num>', delete, name='delete'),
    path('update/budget/<int:id_num>', update_budget, name='update-name'),
    path('home/', home, name='home'),
    path('', index, name='index'),
]

expense_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('activity.urls')),
    path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from .views import register

app_name = 'users'


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

    <head>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- documentation at http://getbootstrap.com/docs/4.1/, alternative themes at https://bootswatch.com/ -->

        <!--Favicon-->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'site.webmanifest' %}">

      <link href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500&family=Inconsolata:wght@400;500;700;900&family=Montserrat:ital,wght@0,400;0,500;1,400;1,500&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <!-- https://favicon.io/emoji-favicons/money-mouth-face/ -->

        <link href="{% static 'css/main.css' %}" rel="stylesheet">

        <title>FinSense: {% block title %}{% endblock %}</title>

    </head>

    <body>

        <nav class="navbar navbar-expand-md navbar-light sticky-top">
            <a class="navbar-brand" href="{% url 'activity:index' %}"><img src="{% static 'img/FinSense@2x.png' %}" alt="logo"></a>
            <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbar" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                {% if user.is_authenticated %}
{#                    <ul class="navbar-nav mr-auto mt-2">#}
{#                        <li class="nav-item"><a class="nav-link" href="/home">Home</a></li>#}
{#                        <li class="nav-item"><a class="nav-link" href="/charts">Charts</a></li>#}
{#                    </ul>#}
                    <ul class="navbar-nav ml-auto mt-2">
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Log out</a></li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav ml-auto mt-2">
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Register</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Sign in</a></li>
                    </ul>
                {% endif %}
            </div>
        </nav>

        {% if messages %}
            <header>
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} border text-center" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            </header>
        {% endif %}

        {% block main %}{% endblock %}


        <footer class="small text-center text-muted border">
            {% block footer %}{% endblock %}
        </footer>


        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/typeit@7.0.4/dist/typeit.min.js"></script>
        <script src="{% static 'js/main.js' %}"></script>
        {% block script %}{% endblock %}
    </body>

</html>